### ISSUE TITLE
Viewer collapses open sections when resizing.

### ISSUE THREAD

**Issue by lrhn** [dart-archive/dartdoc-viewer#126]
I use a tiling window manager. When I switch the browser to a slimmer section of the screen, the DartDoc viewer collapses all open sections. Same thing happens if I resize the window, apparently when I cross 1000px width. That's highly annoying - I find something in the doc, switch to the editor to use it, but then it's collapsed away.

While a view is open, it must never collapse or expand something without explicit user request. Resizing the window is not a request to collapse.

I can understand starting out collapsed on a smaller screen (but since it's useless without further action, I'd actually prefer it to start out open), but after that it's interfering with the use of the page.

**Comment by sethladd** [comment]
Thanks for your report.

However, this issue isn't planned because we are about to release a new dartdoc: https://github.com/dart-lang/dartdoc
